server:
  port: 8082
spring:
  application:
    name: global
  datasource:
    url: jdbc:mysql://localhost:3306/his_mz?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka
feign:
  hystrix:
    enabled: true
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
